<a href="https://colab.research.google.com/github/Nameless8243/PyTorch_DL/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 4])
vector

tensor([7, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> Look at data --> update random numbers`

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7012, 0.6279, 0.7924, 0.6986],
        [0.5618, 0.1825, 0.8423, 0.6559],
        [0.0802, 0.9562, 0.5841, 0.0584]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors you'll run into with PyTorch $ deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # What datatype is the tensor
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype= torch.long)
int_32_tensor

tensor([3, 6, 9])

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype       - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape          - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device  - to get device from a tensor, can use `tensor.device`

In [30]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3272, 0.5137, 0.9656, 0.0313],
        [0.3358, 0.4449, 0.9522, 0.3683],
        [0.3730, 0.1282, 0.0052, 0.3887]])

In [31]:
some_tensor.shape == some_tensor.size()

True

In [32]:
some_tensor.shape

torch.Size([3, 4])

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:  {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3272, 0.5137, 0.9656, 0.0313],
        [0.3358, 0.4449, 0.9522, 0.3683],
        [0.3730, 0.1282, 0.0052, 0.3887]])
Datatype of tensor:  torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [34]:
# Create a tensor
some_tensor_2 = torch.rand(39, 33).type(torch.float16)
some_tensor_2

tensor([[0.3435, 0.8755, 0.7407,  ..., 0.4900, 0.3811, 0.9692],
        [0.5049, 0.1058, 0.5464,  ..., 0.2864, 0.3008, 0.2874],
        [0.5229, 0.3494, 0.9292,  ..., 0.3093, 0.9141, 0.4731],
        ...,
        [0.9414, 0.6421, 0.1554,  ..., 0.8960, 0.1030, 0.4819],
        [0.0053, 0.0365, 0.2281,  ..., 0.2791, 0.9028, 0.4150],
        [0.5488, 0.3613, 0.3052,  ..., 0.9590, 0.7520, 0.8179]],
       dtype=torch.float16)

In [35]:
some_tensor_2.shape

torch.Size([39, 33])

In [36]:
some_tensor_2.dtype

torch.float16

In [37]:
some_tensor_2.ndim

2

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [38]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [40]:
tensor

tensor([1, 2, 3])

In [41]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
%%time
torch.add(tensor, 10)

CPU times: user 112 µs, sys: 18 µs, total: 130 µs
Wall time: 137 µs


tensor([11, 12, 13])

In [44]:
%%time
tensor + 10

CPU times: user 83 µs, sys: 14 µs, total: 97 µs
Wall time: 102 µs


tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise Multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [45]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [46]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [47]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [48]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 415 µs, sys: 69 µs, total: 484 µs
Wall time: 1.6 ms


tensor(14)

In [49]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 78 µs, sys: 0 ns, total: 78 µs
Wall time: 83.2 µs


tensor(14)

### One of the most common errors in deep learning is shape errors

In [50]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B.T)    # torch.mm is the same as torch.matmul (it,s an alias for writing less code)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [51]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one af our tensors using a **transpose**

A **transpose** switchis the axes or dimensions of a given tensor.

In [52]:
print(f"{tensor_B} \n \n {tensor_B.shape}")

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]) 
 
 torch.Size([3, 2])


In [53]:
print(f"{tensor_B.T} \n \n {tensor_B.T.shape}")

tensor([[ 7,  8,  9],
        [10, 11, 12]]) 
 
 torch.Size([2, 3])


In [54]:
# The matrix multiplication operation works when tensor_B is tranposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: torch.mm({tensor_A.shape, tensor_B.T.shape}) --> inner dimensions must match\n")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.mm((torch.Size([3, 2]), torch.Size([2, 3]))) --> inner dimensions must match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [68]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [56]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [57]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [63]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [64]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional in and max

In [69]:
# Find the position of the min value
torch.argmin(x)

tensor(0)

In [71]:
x[0]

tensor(1)

In [70]:
# Find the position af the max value
torch.argmax(x)

tensor(9)

In [72]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape, but keep the same memory as the origital tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

### Reshaping

In [90]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [91]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [92]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [93]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Stacking

> In PyTorch, torch.vstack, torch.stack, and torch.hstack are functions used for stacking tensors along different dimensions.

> These functions are useful for combining tensors in various ways, depending on the desired shape and dimensionality of the resulting tensor.




> `torch.stack`: This function stacks tensors along a new dimension. It creates a new dimension and stacks the tensors along that dimension.

In [107]:
# Create two tensors
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Stack tensors along a new dimension
result_dim0= torch.stack((a, b), dim=0)
result_dim1 = torch.stack((a, b), dim=1)

print(f"dim=0: \n {result_dim0}\n")
print(f"dim=1: \n {result_dim1}")

dim=0: 
 tensor([[1, 2, 3],
        [4, 5, 6]])

dim=1: 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


> `torch.vstack`: This function vertically stacks tensors along the first dimension (rows). It concatenates tensors along the row dimension.

In [98]:
# Create two tensors
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])

# Vertically stack tensors
result = torch.vstack((a, b))
print(result)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


> `torch.hstack`: This function horizontally stacks tensors along the second dimension (columns). It concatenates tensors along the column dimension.

In [100]:
# Create two tensors
a = torch.tensor([[1, 2],
                  [3, 4]])
b = torch.tensor([[5, 6],
                  [7, 8]])

# Horizontally stack tensors
result = torch.hstack((a, b))
print(result)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### Squeeze & unsqueeze

> In PyTorch, `squeeze` and `unsqueeze` are functions used to change the shape of a tensor by adding or removing dimensions with size 1.

> These functions are useful for manipulating tensor shapes to match the required input shapes for operations or for broadcasting tensors during arithmetic operations.

> `squeeze`: This function removes dimensions with size 1 from the tensor.

In [115]:
# Create a tensor with shape (1, 3, 1, 4)
tensor = torch.randn(1, 3, 1, 4)

# Squeeze the tensor to remove dimensions with size 1
squeezed_tensor = torch.squeeze(tensor)

print("Original shape:", tensor.shape)
print("Squeezed shape:", squeezed_tensor.shape)

Original shape: torch.Size([1, 3, 1, 4])
Squeezed shape: torch.Size([3, 4])


> `unsqueeze`: This function adds a dimension with size 1 at the specified position in the tensor's shape.

In [114]:
# Create a tensor with shape (3, 4)
tensor = torch.randn(3, 4)

# Unsqueeze the tensor along dimension 0
unsqueezed_tensor = torch.unsqueeze(tensor, dim=0)

print("Original shape:", tensor.shape)
print("Unsqueezed shape:", unsqueezed_tensor.shape)

Original shape: torch.Size([3, 4])
Unsqueezed shape: torch.Size([1, 3, 4])


In [123]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape:   {x_original.shape}\n")
print(f"New shape:        {x_permuted.shape}")  # [colour_channels, height, width]

Previous shape:   torch.Size([224, 224, 3])

New shape:        torch.Size([3, 224, 224])


In [126]:
x_original[0, 0, 0] = 33

In [127]:
x_permuted[0, 0, 0]

tensor(33.)

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy.

In [130]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [131]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [132]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [135]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [136]:
# You can also use ":" to select "all" of a target dimensions
x[:, 0]

tensor([[1, 2, 3]])

In [137]:
# Get all the values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [138]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [139]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])