<a href="https://colab.research.google.com/github/Nameless8243/PyTorch_DL/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 4])
vector

tensor([7, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> Look at data --> update random numbers`

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7076, 0.1734, 0.4646, 0.1186],
        [0.9902, 0.5096, 0.6781, 0.3915],
        [0.5286, 0.2063, 0.3512, 0.6714]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors you'll run into with PyTorch $ deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [38]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # What datatype is the tensor
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [46]:
int_32_tensor = torch.tensor([3, 6, 9], dtype= torch.long)
int_32_tensor

tensor([3, 6, 9])

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype       - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape          - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device  - to get device from a tensor, can use `tensor.device`

In [48]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2684, 0.2115, 0.5858, 0.0717],
        [0.7385, 0.5147, 0.0793, 0.8712],
        [0.1535, 0.9152, 0.3375, 0.9351]])

In [50]:
some_tensor.shape == some_tensor.size()

True

In [51]:
some_tensor.shape

torch.Size([3, 4])

In [53]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:  {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2684, 0.2115, 0.5858, 0.0717],
        [0.7385, 0.5147, 0.0793, 0.8712],
        [0.1535, 0.9152, 0.3375, 0.9351]])
Datatype of tensor:  torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [61]:
# Create a tensor
some_tensor_2 = torch.rand(39, 33).type(torch.float16)
some_tensor_2

tensor([[0.7583, 0.6826, 0.9067,  ..., 0.1893, 0.6284, 0.2085],
        [0.7256, 0.3511, 0.5791,  ..., 0.5068, 0.2395, 0.3108],
        [0.4641, 0.7720, 0.8867,  ..., 0.2220, 0.9160, 0.3552],
        ...,
        [0.1205, 0.9795, 0.5791,  ..., 0.9365, 0.7217, 0.2269],
        [0.2208, 0.3779, 0.8682,  ..., 0.0480, 0.6860, 0.9463],
        [0.5371, 0.1375, 0.1417,  ..., 0.0866, 0.8794, 0.4819]],
       dtype=torch.float16)

In [56]:
some_tensor_2.shape

torch.Size([39, 33])

In [57]:
some_tensor_2.dtype

torch.float32

In [58]:
some_tensor_2.ndim

2

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [73]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [74]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [75]:
tensor

tensor([1, 2, 3])

In [76]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [77]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [79]:
torch.add(tensor, 10)

tensor([11, 12, 13])