<a href="https://colab.research.google.com/github/Nameless8243/PyTorch_DL/blob/main/00_pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
random_seed = 42
torch.manual_seed(random_seed)
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

print(f"Tensor B:\n{tensor_A}\n")
print(f"Tensor A:\n{tensor_B}")

Tensor B:
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])

Tensor A:
tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071]])


In [3]:
print(f"Tensor B:\n{tensor_B}\n")
print(f"Tensor B.T:\n{tensor_B.T}")

Tensor B:
tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071]])

Tensor B.T:
tensor([[0.1952],
        [0.0050],
        [0.3068],
        [0.1165],
        [0.9103],
        [0.6440],
        [0.7071]])


In [4]:
torch.mm(tensor_A, tensor_B.T)

tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]])

In [5]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)

# Create two random tensors
tensor_C = torch.rand(4, 4)
tensor_D = torch.rand(1, 4)

# Matrix multiply tensors
torch.mm(tensor_C, tensor_D.T)

tensor([[1.0123],
        [1.0537],
        [0.9933],
        [0.3444]])

In [6]:
# Set random seed on the GPU
seed = 1234
torch.manual_seed(random_seed)
if torch.cuda.is_available():
  torch.cuda.manual_seed(seed)

In [10]:
torch.manual_seed(1234)
tensor_E = torch.rand(2, 3).to("cuda")
tensor_F = torch.rand(2, 3).to("cuda")

print(f"Tensor E:\n{tensor_E}\n")
print(f"Tensor F:\n{tensor_F}")

Tensor E:
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

Tensor F:
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [12]:
matmul_EF = torch.mm(tensor_E, tensor_F.T)

In [13]:
torch.max(matmul_EF)

tensor(0.5617, device='cuda:0')

In [14]:
torch.min(matmul_EF)

tensor(0.3647, device='cuda:0')

In [15]:
torch.argmax(matmul_EF)

tensor(3, device='cuda:0')

In [16]:
torch.argmin(matmul_EF)

tensor(0, device='cuda:0')

In [28]:
torch.manual_seed(7)
tensor_G = torch.rand(1, 1, 1, 10)
tensor_G, tensor_G.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [26]:
tensor_H = tensor_G.squeeze()

In [29]:
tensor_H, tensor_H.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))